#!/usr/bin/env bash

set -e

go get github.com/jteeuwen/go-bindata/...

echo " Generating i18n Resource file"
go-bindata -pkg resources -ignore ".go" -o ./resources/i18n_resources.go ./i18n/resources/...
